name: Release on stage environment

on:
  workflow_call:
    inputs:
      version_to_deploy:
        description: 'What version to deploy'
        required: true
        type: string
        default: 'latest'

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: print
      run: echo test ${{ inputs.version_to_deploy }}
      