name: Release on stage environment

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: print
      run: echo test ${{ inputs.config-path }}
      